eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: localhost
 
mi:
  saludo : hola desde repositorio local
  lista.valores: uno,dos,tres

db:
  claveValor : "{\
  urlBase: 'urlBase',\
  nombre: 'nombre',\
  port: 'port'}"
  host: "localhost"
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"
